# Generated by Django 3.1.7 on 2021-03-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250, verbose_name='Вопрос')),
                ('answer', models.CharField(max_length=250, verbose_name='Ответ')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='Идентификатор пользователя')),
            ],
        ),
        migrations.AlterModelOptions(
            name='questionnaire',
            options={'verbose_name': 'Опрос', 'verbose_name_plural': 'Опросы'},
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='number_of_questions',
            field=models.IntegerField(default=1, verbose_name='Количество вопросов'),
            preserve_default=False,
        ),
    ]
