# Generated by Django 3.1.7 on 2021-03-05 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0002_auto_20210304_1212'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Record',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='type_of_question',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='number_of_questions',
        ),
        migrations.AddField(
            model_name='question',
            name='question_category',
            field=models.CharField(choices=[('MC', 'Multichoice'), ('CN', 'Choose N'), ('TX', 'Text')], default=None, max_length=2, verbose_name='Question category'),
        ),
        migrations.AddField(
            model_name='question',
            name='questionnaire',
            field=models.ManyToManyField(to='quest.Questionnaire'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(default=None, max_length=250, verbose_name='Текст вопроса'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='title',
            field=models.CharField(default=None, max_length=50, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='MultiChoiceAnswer',
            fields=[
                ('answer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quest.answer')),
                ('answer', models.IntegerField(choices=[('1', 'Least'), ('2', 'Less than average'), ('3', 'Average'), ('4', 'More than average'), ('5', 'Most')])),
            ],
            bases=('quest.answer',),
        ),
    ]
