# Generated by Django 3.1.7 on 2021-03-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0003_auto_20210305_1332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_text',
            field=models.CharField(default=None, max_length=250, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_category',
            field=models.CharField(choices=[('MC', 'Выберите один'), ('CS', 'Выберите несколько'), ('TX', 'Ответьте текстом')], default=None, max_length=2, verbose_name='Тип вопроса'),
        ),
        migrations.DeleteModel(
            name='MultiChoiceAnswer',
        ),
    ]
