# Generated by Django 3.1.7 on 2021-03-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0004_auto_20210305_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_question',
            field=models.ManyToManyField(to='quest.Question'),
        ),
    ]
