# Generated by Django 3.1.7 on 2021-03-06 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0007_auto_20210306_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='dictionary',
            new_name='dic',
        ),
    ]
