# Generated by Django 3.1.7 on 2021-03-06 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0008_auto_20210306_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='dic',
        ),
    ]
