# Generated by Django 3.1.7 on 2021-03-06 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0009_remove_record_dic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='number_of_questions',
        ),
        migrations.RemoveField(
            model_name='record',
            name='questionnaire',
        ),
        migrations.RemoveField(
            model_name='record',
            name='user_id',
        ),
    ]
