# Generated by Django 3.1.7 on 2021-03-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0011_auto_20210306_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='dic',
            field=models.CharField(default=None, max_length=250, verbose_name='Словарь'),
        ),
        migrations.AlterField(
            model_name='record',
            name='number_of_questions',
            field=models.CharField(default=None, max_length=250, verbose_name='Количество вопросов'),
        ),
        migrations.AlterField(
            model_name='record',
            name='questionnaire',
            field=models.CharField(default=None, max_length=250, verbose_name='Опрос'),
        ),
        migrations.AlterField(
            model_name='record',
            name='user_id',
            field=models.CharField(default=None, max_length=250, verbose_name='Айди'),
        ),
    ]
