# Generated by Django 3.1.7 on 2021-03-06 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0012_auto_20210306_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='dic',
        ),
        migrations.RemoveField(
            model_name='record',
            name='number_of_questions',
        ),
        migrations.RemoveField(
            model_name='record',
            name='questionnaire',
        ),
    ]
