# Generated by Django 3.1.7 on 2021-03-06 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0015_auto_20210306_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='questionnaire',
        ),
    ]
