# Generated by Django 3.1.7 on 2021-03-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0016_remove_record_questionnaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='questionnaire',
            field=models.CharField(default=None, max_length=250, verbose_name='Опрос'),
        ),
    ]
