# Generated by Django 3.1.7 on 2021-03-06 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0017_record_questionnaire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='questionnaire',
            new_name='abababab',
        ),
    ]
