# Generated by Django 3.1.7 on 2021-03-06 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0018_auto_20210306_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='abababab',
        ),
    ]
