# Generated by Django 3.1.7 on 2021-03-06 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0023_record_abababab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='abababab',
        ),
    ]
