# Generated by Django 3.1.7 on 2021-03-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0024_remove_record_abababab'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='abababab',
            field=models.CharField(default=None, max_length=250, verbose_name='Название'),
        ),
    ]
