# Generated by Django 3.1.7 on 2021-03-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0025_record_abababab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='abababab',
            field=models.CharField(default=None, max_length=250, null=True, verbose_name='Название'),
        ),
    ]
