# Generated by Django 3.1.7 on 2021-03-06 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0026_auto_20210306_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='abababab',
        ),
    ]
