# Generated by Django 3.1.7 on 2021-03-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0030_record_number_of_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='number_of_questions',
            field=models.CharField(default=None, max_length=250, null=True, verbose_name='Количество вопросов'),
        ),
    ]
