# Generated by Django 3.1.7 on 2021-03-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0033_record_number_of_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='dictionary',
            field=models.CharField(default=None, max_length=250, null=True, verbose_name='Data'),
        ),
    ]
